# Generated by Django 3.2.4 on 2021-06-15 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('carrier', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.carrier')),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('cost', models.FloatField()),
                ('finish', models.ManyToManyField(max_length=40, related_name='interval_finishes', to='api.Station')),
                ('start', models.ManyToManyField(max_length=40, related_name='interval_starts', to='api.Station')),
            ],
        ),
        migrations.CreateModel(
            name='Carriage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('tickets', models.BinaryField()),
                ('route', models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.PROTECT, to='api.route')),
            ],
        ),
    ]
