# Generated by Django 3.2.4 on 2021-06-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_carriage_carrier_interval_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='finish',
            field=models.ManyToManyField(max_length=40, related_name='route_finishes', to='api.Station'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_sequence',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='start',
            field=models.ManyToManyField(max_length=40, related_name='route_starts', to='api.Station'),
        ),
    ]
